### ISSUE TITLE
OOC portal check - giving both option to enter and flagging as illegal

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#255]

**Comment by AgonyAunt** [comment]
Should be fixed, or at least alleviated some. Wait for feedback.

**Comment by SerenaSV** [comment]
As of today, I still get both options in the portal conversation.
Still able to enter without problem, anyway.

**Comment by AgonyAunt** [comment]
Thanks for the info.

**Comment by AgonyAunt** [comment]
Needs testing and figuring out what is going on. I've checked the convo and script, no idea why.

**Comment by SerenaSV** [comment]
Should I find a DM online, I'll ask them to check the character in case there's something they may find out?

**Comment by AgonyAunt** [comment]
Don't think so, its a script or convo problem probably. I might take a look at it again some time. Even though i'm more or less retiring, ill still help out with things from time to time.

**Comment by SerenaSV** [comment]
I have an update on this, if it may be useful!
The portal now doesn't give me the illegal flagging anymore, unfortunately, two things happened and I don't know exactly which one may have solved the issue:
- first and most notably, I cashed out all the book the character was carrying with him (almost 600)
- second, A DM replaced my character's robe of the Archimagi after the mirror broke it today. The robe itself was fine until before the accident, still, I have no means to say if that item could have been the original reason for the problem.

aand, hope to see you around as a player maybe! After all the work, you gotta play it a little more!!

**Comment by AgonyAunt** [comment]
Anyone know if this is still happening?
